---
version: 3
build_arg_defaults:
 EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8'


ansible_config: './ansible.cfg'
dependencies:
 galaxy: requirements.yml
 python: requirements.txt


additional_build_steps:
 prepend: |
   RUN pip3 install --upgrade pip setuptools
 append:
   - RUN ls -la /etc