name: Link Check
on:
  schedule: [{ cron: '0 3 * * 1' }]
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
